## PLEASE DO NOT MODIFIC THIS document
## FILE CORE - TO BE MODIFIED MUST CONTACT THE CORE TEAM.

## Site Settings

title: MaioBlog
description: Acontece ao seu redor
lead: Junte-se a nós e leve as notícias para sua turma ou turno. Todos devem saber.
lead-button: Saiba mais
lead-btn: btn-outline-info
